<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateSelectDBadp" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/empUpdateDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:client="http://xmlns.oracle.com/DatabaseApplication/UpdateEmployeeService/EmpUpdateProcess"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseApplication/UpdateEmployeeService/empUpdateDB"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/EmpUpdateProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EmpCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateSelectDBadp"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/empUpdateDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EmpCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/empUpdateDB"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [THU MAY 24 13:54:08 EDT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:EmpCollection>
         <xsl:for-each select="/ns0:EmpCollection/ns0:Emp">
            <tns:Emp>
               <tns:empno>
                  <xsl:value-of select="ns0:empno"/>
               </tns:empno>
               <xsl:if test="ns0:ename">
                  <tns:ename>
                     <xsl:if test="ns0:ename/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ename/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ename"/>
                  </tns:ename>
               </xsl:if>
               <xsl:if test="ns0:job">
                  <tns:job>
                     <xsl:if test="ns0:job/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:job/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:job"/>
                  </tns:job>
               </xsl:if>
               <xsl:if test="ns0:mgr">
                  <tns:mgr>
                     <xsl:if test="ns0:mgr/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:mgr/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:mgr"/>
                  </tns:mgr>
               </xsl:if>
               <xsl:if test="ns0:hiredate">
                  <tns:hiredate>
                     <xsl:if test="ns0:hiredate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:hiredate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:hiredate"/>
                  </tns:hiredate>
               </xsl:if>
               <xsl:if test="ns0:sal">
                  <tns:sal>
                     <xsl:if test="ns0:sal/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:sal/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:sal"/>
                  </tns:sal>
               </xsl:if>
               <xsl:if test="ns0:comm">
                  <tns:comm>
                     <xsl:if test="ns0:comm/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:comm/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:comm"/>
                  </tns:comm>
               </xsl:if>
               <xsl:if test="ns0:deptno">
                  <tns:deptno>
                     <xsl:if test="ns0:deptno/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:deptno/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:deptno"/>
                  </tns:deptno>
               </xsl:if>
            </tns:Emp>
         </xsl:for-each>
      </tns:EmpCollection>
   </xsl:template>
</xsl:stylesheet>
