<wsdl:definitions
     name="Dbadaptor"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseApplication/FileDatabaseprj/Dbadaptor"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseApplication/FileDatabaseprj/Dbadaptor"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/Dbadaptor"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Dbadaptor_plt" >
    <plt:role name="Dbadaptor_role" >
      <plt:portType name="tns:Dbadaptor_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Dbadaptor" schemaLocation="../Schemas/Dbadaptor_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmpCollection_msg">
        <wsdl:part name="EmpCollection" element="top:EmpCollection"/>
    </wsdl:message>
    <wsdl:portType name="Dbadaptor_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:EmpCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
